package fh;

import lf.t;

/* renamed from: fh.a  reason: case insensitive filesystem */
public interface C5934a {

    /* renamed from: fh.a$a  reason: collision with other inner class name */
    public static final class C0996a {
        public static Object[] a(C5934a aVar, int i10) {
            throw new t("Generated by Android Extensions automatically");
        }
    }
}
